/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Gameboy(props) {
  const { nodes, materials } = useGLTF("/console_body.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube3_gembBOI__0.geometry}
        material={materials["gembBOI.001"]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cross.geometry}
        material={materials["BUTT_ON.001"]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.butn_1.geometry}
        material={materials["BUTT_ON.001"]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.btn_2.geometry}
        material={materials["BUTT_ON.001"]}
        scale={0.006}
      />
    </group>
  );
}

useGLTF.preload("/console_body.glb");
